"""
Synthetic Data Generator for LineageIQ
=============================================

Generates a realistic e-commerce data warehouse with:
  - 25 tables across 4 layers (raw, staging, curated, reporting)
  - Columns with data types and natural-language descriptions
  - 15 ETL jobs that define lineage (reads from → writes to)

The generated data represents a fictional e-commerce company called "ShopStream"
that processes orders, manages customers, handles payments, and tracks shipments.

Output:
  - data/synthetic/tables.json      → table definitions with descriptions
  - data/synthetic/columns.json     → column definitions with descriptions
  - data/synthetic/jobs.json        → ETL job definitions
  - data/synthetic/lineage_edges.json → which jobs read/write which tables

Usage:
  python scripts/data_generator.py

Why synthetic data?
  We don't need (and shouldn't use) real company data. This script generates
  a reproducible dataset that mirrors a real data warehouse closely enough
  to demonstrate the lineage system. Having the generator in the repo also
  shows engineering care — anyone can reproduce the demo.
"""

import json
import os
from datetime import datetime, timedelta
import random


# =============================================================================
# OUTPUT DIRECTORY
# =============================================================================
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "synthetic")


# =============================================================================
# TABLE DEFINITIONS
# =============================================================================
# Organized in 4 layers, like a real data warehouse:
#   1. raw_*       — Raw ingestion tables (data lands here first from source systems)
#   2. stg_*       — Staging tables (cleaned, validated, deduped)
#   3. curated_*   — Curated/conformed tables (business logic applied, join-ready)
#   4. rpt_*       — Reporting tables (aggregated, ready for dashboards)
#
# Each table has a description that will later be embedded into the vector DB
# for semantic search ("which tables relate to customer refunds?").

TABLES = [
    # ---- RAW LAYER (data lands here from source systems) ----
    {
        "name": "raw_orders",
        "layer": "raw",
        "description": "Raw order data ingested from the ShopStream transactional database. Contains every order placed on the platform, including pending, completed, cancelled, and refunded orders. No transformations applied — this is the source-of-truth landing zone.",
        "columns": [
            {"name": "order_id", "type": "STRING", "description": "Unique identifier for each order, generated by the source system"},
            {"name": "customer_id", "type": "STRING", "description": "Foreign key to the customer who placed this order"},
            {"name": "order_date", "type": "TIMESTAMP", "description": "Date and time when the order was placed"},
            {"name": "total_amount", "type": "DECIMAL", "description": "Total monetary value of the order in USD"},
            {"name": "status", "type": "STRING", "description": "Current order status: pending, confirmed, shipped, delivered, cancelled, refunded"},
            {"name": "channel", "type": "STRING", "description": "Sales channel: web, mobile_app, marketplace, phone"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested into the data warehouse"},
        ],
    },
    {
        "name": "raw_customers",
        "layer": "raw",
        "description": "Raw customer profile data from the CRM system. Includes all registered customers with their contact details and account metadata. Updated daily via full extract.",
        "columns": [
            {"name": "customer_id", "type": "STRING", "description": "Unique customer identifier from the CRM system"},
            {"name": "email", "type": "STRING", "description": "Customer email address (primary contact method)"},
            {"name": "first_name", "type": "STRING", "description": "Customer's first name"},
            {"name": "last_name", "type": "STRING", "description": "Customer's last name"},
            {"name": "signup_date", "type": "DATE", "description": "Date the customer created their account"},
            {"name": "country", "type": "STRING", "description": "Customer's country of residence (ISO 3166-1 alpha-2)"},
            {"name": "segment", "type": "STRING", "description": "Customer segment: standard, premium, vip"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },
    {
        "name": "raw_payments",
        "layer": "raw",
        "description": "Raw payment transactions from the payment gateway (Stripe). Each record represents a single payment attempt, which may succeed or fail. Multiple payment attempts can exist for a single order.",
        "columns": [
            {"name": "payment_id", "type": "STRING", "description": "Unique payment transaction identifier from Stripe"},
            {"name": "order_id", "type": "STRING", "description": "Order this payment is associated with"},
            {"name": "payment_method", "type": "STRING", "description": "Payment method: credit_card, debit_card, paypal, bank_transfer, apple_pay"},
            {"name": "amount", "type": "DECIMAL", "description": "Payment amount in USD"},
            {"name": "currency", "type": "STRING", "description": "Original currency code (ISO 4217)"},
            {"name": "status", "type": "STRING", "description": "Payment status: pending, succeeded, failed, refunded"},
            {"name": "processed_at", "type": "TIMESTAMP", "description": "Timestamp when the payment was processed by the gateway"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },
    {
        "name": "raw_products",
        "layer": "raw",
        "description": "Raw product catalog data from the inventory management system. Contains all products ever listed on the platform, including discontinued items.",
        "columns": [
            {"name": "product_id", "type": "STRING", "description": "Unique product identifier (SKU)"},
            {"name": "product_name", "type": "STRING", "description": "Display name of the product"},
            {"name": "category", "type": "STRING", "description": "Product category: electronics, clothing, home, sports, books"},
            {"name": "price", "type": "DECIMAL", "description": "Current listed price in USD"},
            {"name": "cost", "type": "DECIMAL", "description": "Cost of goods sold (COGS) per unit"},
            {"name": "supplier_id", "type": "STRING", "description": "Foreign key to the supplier/vendor"},
            {"name": "is_active", "type": "BOOLEAN", "description": "Whether the product is currently available for sale"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },
    {
        "name": "raw_order_items",
        "layer": "raw",
        "description": "Raw line items for each order. Each record is one product within an order (an order can contain multiple items). Links orders to products with quantity and pricing.",
        "columns": [
            {"name": "order_item_id", "type": "STRING", "description": "Unique line item identifier"},
            {"name": "order_id", "type": "STRING", "description": "Parent order this item belongs to"},
            {"name": "product_id", "type": "STRING", "description": "Product purchased"},
            {"name": "quantity", "type": "INTEGER", "description": "Number of units ordered"},
            {"name": "unit_price", "type": "DECIMAL", "description": "Price per unit at time of purchase (may differ from current catalog price)"},
            {"name": "discount", "type": "DECIMAL", "description": "Discount applied to this line item"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },
    {
        "name": "raw_shipping_events",
        "layer": "raw",
        "description": "Raw shipping and delivery tracking events from logistics partners. Each record is a single tracking event (e.g., 'picked up', 'in transit', 'delivered'). Multiple events per shipment.",
        "columns": [
            {"name": "event_id", "type": "STRING", "description": "Unique tracking event identifier"},
            {"name": "order_id", "type": "STRING", "description": "Order this shipment event relates to"},
            {"name": "carrier", "type": "STRING", "description": "Shipping carrier: fedex, ups, dhl, usps"},
            {"name": "tracking_number", "type": "STRING", "description": "Carrier tracking number"},
            {"name": "event_type", "type": "STRING", "description": "Event type: label_created, picked_up, in_transit, out_for_delivery, delivered, returned"},
            {"name": "event_timestamp", "type": "TIMESTAMP", "description": "When this tracking event occurred"},
            {"name": "location", "type": "STRING", "description": "Location where the event occurred (city, state)"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },
    {
        "name": "raw_suppliers",
        "layer": "raw",
        "description": "Raw supplier/vendor master data. Contains information about companies that supply products to ShopStream.",
        "columns": [
            {"name": "supplier_id", "type": "STRING", "description": "Unique supplier identifier"},
            {"name": "supplier_name", "type": "STRING", "description": "Company name of the supplier"},
            {"name": "contact_email", "type": "STRING", "description": "Primary contact email for the supplier"},
            {"name": "country", "type": "STRING", "description": "Supplier's country of operation"},
            {"name": "lead_time_days", "type": "INTEGER", "description": "Average lead time in days for order fulfillment"},
            {"name": "rating", "type": "DECIMAL", "description": "Internal supplier rating (1-5 scale)"},
            {"name": "ingested_at", "type": "TIMESTAMP", "description": "Timestamp when this record was ingested"},
        ],
    },

    # ---- STAGING LAYER (cleaned, validated, deduped) ----
    {
        "name": "stg_orders",
        "layer": "staging",
        "description": "Staged orders — cleaned and validated from raw_orders. Invalid orders removed, data types standardized, duplicates eliminated. Ready for business logic application.",
        "columns": [
            {"name": "order_id", "type": "STRING", "description": "Unique order identifier (validated, no nulls)"},
            {"name": "customer_id", "type": "STRING", "description": "Validated customer foreign key"},
            {"name": "order_date", "type": "TIMESTAMP", "description": "Order timestamp (standardized to UTC)"},
            {"name": "total_amount", "type": "DECIMAL", "description": "Order total (validated: must be > 0)"},
            {"name": "status", "type": "STRING", "description": "Standardized order status enum"},
            {"name": "channel", "type": "STRING", "description": "Standardized sales channel"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },
    {
        "name": "stg_customers",
        "layer": "staging",
        "description": "Staged customers — cleaned from raw_customers. Email addresses validated, names standardized, country codes normalized to ISO format.",
        "columns": [
            {"name": "customer_id", "type": "STRING", "description": "Unique customer ID (validated)"},
            {"name": "email", "type": "STRING", "description": "Validated and lowercased email"},
            {"name": "full_name", "type": "STRING", "description": "Combined first + last name"},
            {"name": "signup_date", "type": "DATE", "description": "Account creation date"},
            {"name": "country_code", "type": "STRING", "description": "Normalized ISO country code"},
            {"name": "segment", "type": "STRING", "description": "Customer segment (validated enum)"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },
    {
        "name": "stg_payments",
        "layer": "staging",
        "description": "Staged payments — cleaned from raw_payments. Amounts converted to USD, failed payment attempts flagged, duplicates removed based on payment gateway idempotency keys.",
        "columns": [
            {"name": "payment_id", "type": "STRING", "description": "Unique payment ID (validated)"},
            {"name": "order_id", "type": "STRING", "description": "Associated order ID"},
            {"name": "payment_method", "type": "STRING", "description": "Standardized payment method"},
            {"name": "amount_usd", "type": "DECIMAL", "description": "Payment amount converted to USD"},
            {"name": "status", "type": "STRING", "description": "Standardized payment status"},
            {"name": "processed_at", "type": "TIMESTAMP", "description": "Processing timestamp (UTC)"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },
    {
        "name": "stg_products",
        "layer": "staging",
        "description": "Staged products — cleaned from raw_products. Product names trimmed, categories standardized, prices validated. Discontinued products still included but flagged.",
        "columns": [
            {"name": "product_id", "type": "STRING", "description": "Unique product SKU (validated)"},
            {"name": "product_name", "type": "STRING", "description": "Cleaned product name"},
            {"name": "category", "type": "STRING", "description": "Standardized product category"},
            {"name": "price_usd", "type": "DECIMAL", "description": "Current price in USD"},
            {"name": "cost_usd", "type": "DECIMAL", "description": "COGS in USD"},
            {"name": "is_active", "type": "BOOLEAN", "description": "Whether product is currently listed"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },
    {
        "name": "stg_order_items",
        "layer": "staging",
        "description": "Staged order line items — cleaned from raw_order_items. Quantities validated (must be > 0), orphaned items (no matching order) removed.",
        "columns": [
            {"name": "order_item_id", "type": "STRING", "description": "Unique line item ID"},
            {"name": "order_id", "type": "STRING", "description": "Parent order ID (validated FK)"},
            {"name": "product_id", "type": "STRING", "description": "Product ID (validated FK)"},
            {"name": "quantity", "type": "INTEGER", "description": "Quantity ordered (validated > 0)"},
            {"name": "unit_price_usd", "type": "DECIMAL", "description": "Unit price at time of purchase (USD)"},
            {"name": "discount_usd", "type": "DECIMAL", "description": "Discount applied (USD)"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },
    {
        "name": "stg_shipping",
        "layer": "staging",
        "description": "Staged shipping events — cleaned from raw_shipping_events. Events deduplicated, timestamps standardized to UTC, carrier names normalized.",
        "columns": [
            {"name": "event_id", "type": "STRING", "description": "Unique event ID"},
            {"name": "order_id", "type": "STRING", "description": "Associated order"},
            {"name": "carrier", "type": "STRING", "description": "Normalized carrier name"},
            {"name": "tracking_number", "type": "STRING", "description": "Tracking number"},
            {"name": "event_type", "type": "STRING", "description": "Standardized event type enum"},
            {"name": "event_timestamp", "type": "TIMESTAMP", "description": "Event time (UTC)"},
            {"name": "loaded_at", "type": "TIMESTAMP", "description": "When this staging record was created"},
        ],
    },

    # ---- CURATED LAYER (business logic applied, conformed dimensions) ----
    {
        "name": "curated_orders",
        "layer": "curated",
        "description": "Conformed order fact table — the single source of truth for order analytics. Combines staged orders with payment status and shipping status. Each row is one order with its final state. Used by all downstream reporting.",
        "columns": [
            {"name": "order_id", "type": "STRING", "description": "Order ID (primary key)"},
            {"name": "customer_id", "type": "STRING", "description": "Customer dimension key"},
            {"name": "order_date", "type": "TIMESTAMP", "description": "Order placement date"},
            {"name": "total_amount_usd", "type": "DECIMAL", "description": "Total order value in USD"},
            {"name": "payment_status", "type": "STRING", "description": "Final payment status (from stg_payments)"},
            {"name": "shipping_status", "type": "STRING", "description": "Latest shipping status (from stg_shipping)"},
            {"name": "order_status", "type": "STRING", "description": "Final order status"},
            {"name": "channel", "type": "STRING", "description": "Sales channel"},
            {"name": "is_refunded", "type": "BOOLEAN", "description": "Whether this order was fully or partially refunded"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "Last update timestamp"},
        ],
    },
    {
        "name": "curated_customers",
        "layer": "curated",
        "description": "Conformed customer dimension — enriched customer profiles with computed metrics. Includes lifetime value, order count, and current segment. Used for customer analytics and segmentation.",
        "columns": [
            {"name": "customer_id", "type": "STRING", "description": "Customer ID (primary key)"},
            {"name": "full_name", "type": "STRING", "description": "Customer full name"},
            {"name": "email", "type": "STRING", "description": "Contact email"},
            {"name": "country_code", "type": "STRING", "description": "Country of residence"},
            {"name": "segment", "type": "STRING", "description": "Current customer segment"},
            {"name": "signup_date", "type": "DATE", "description": "Account creation date"},
            {"name": "total_orders", "type": "INTEGER", "description": "Lifetime order count"},
            {"name": "lifetime_value_usd", "type": "DECIMAL", "description": "Total spend across all orders"},
            {"name": "first_order_date", "type": "DATE", "description": "Date of first purchase"},
            {"name": "last_order_date", "type": "DATE", "description": "Date of most recent purchase"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "Last update timestamp"},
        ],
    },
    {
        "name": "curated_products",
        "layer": "curated",
        "description": "Conformed product dimension — enriched with sales performance metrics. Includes total units sold, revenue generated, and profit margin. Used for product analytics and inventory decisions.",
        "columns": [
            {"name": "product_id", "type": "STRING", "description": "Product SKU (primary key)"},
            {"name": "product_name", "type": "STRING", "description": "Product display name"},
            {"name": "category", "type": "STRING", "description": "Product category"},
            {"name": "price_usd", "type": "DECIMAL", "description": "Current listed price"},
            {"name": "cost_usd", "type": "DECIMAL", "description": "COGS per unit"},
            {"name": "margin_pct", "type": "DECIMAL", "description": "Profit margin percentage: (price - cost) / price"},
            {"name": "total_units_sold", "type": "INTEGER", "description": "Lifetime units sold"},
            {"name": "total_revenue_usd", "type": "DECIMAL", "description": "Lifetime revenue from this product"},
            {"name": "is_active", "type": "BOOLEAN", "description": "Whether product is available"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "Last update timestamp"},
        ],
    },
    {
        "name": "curated_order_items",
        "layer": "curated",
        "description": "Conformed order line items fact table — each row is one product within an order, enriched with product details and computed line totals. Bridge table between orders and products.",
        "columns": [
            {"name": "order_item_id", "type": "STRING", "description": "Line item ID (primary key)"},
            {"name": "order_id", "type": "STRING", "description": "Parent order FK"},
            {"name": "product_id", "type": "STRING", "description": "Product FK"},
            {"name": "quantity", "type": "INTEGER", "description": "Units ordered"},
            {"name": "unit_price_usd", "type": "DECIMAL", "description": "Unit price at purchase"},
            {"name": "line_total_usd", "type": "DECIMAL", "description": "quantity × unit_price - discount"},
            {"name": "discount_usd", "type": "DECIMAL", "description": "Discount on this line"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "Last update timestamp"},
        ],
    },

    # ---- REPORTING LAYER (aggregated, dashboard-ready) ----
    {
        "name": "rpt_daily_sales",
        "layer": "reporting",
        "description": "Daily sales summary report — aggregated from curated_orders and curated_order_items. One row per day with total revenue, order count, average order value, and refund rate. Powers the executive sales dashboard.",
        "columns": [
            {"name": "report_date", "type": "DATE", "description": "Calendar date"},
            {"name": "total_orders", "type": "INTEGER", "description": "Number of orders placed"},
            {"name": "total_revenue_usd", "type": "DECIMAL", "description": "Total revenue for the day"},
            {"name": "avg_order_value_usd", "type": "DECIMAL", "description": "Average order value"},
            {"name": "refund_rate", "type": "DECIMAL", "description": "Percentage of orders refunded"},
            {"name": "top_channel", "type": "STRING", "description": "Highest-revenue sales channel for the day"},
            {"name": "generated_at", "type": "TIMESTAMP", "description": "When this report was generated"},
        ],
    },
    {
        "name": "rpt_customer_segments",
        "layer": "reporting",
        "description": "Customer segmentation report — aggregated from curated_customers and curated_orders. Breaks down customer base by segment (standard/premium/vip) with cohort metrics. Used for marketing targeting and retention analysis.",
        "columns": [
            {"name": "segment", "type": "STRING", "description": "Customer segment"},
            {"name": "customer_count", "type": "INTEGER", "description": "Number of customers in segment"},
            {"name": "avg_lifetime_value_usd", "type": "DECIMAL", "description": "Average LTV for segment"},
            {"name": "avg_order_frequency", "type": "DECIMAL", "description": "Average orders per customer"},
            {"name": "churn_rate", "type": "DECIMAL", "description": "Percentage of customers inactive 90+ days"},
            {"name": "generated_at", "type": "TIMESTAMP", "description": "When this report was generated"},
        ],
    },
    {
        "name": "rpt_product_performance",
        "layer": "reporting",
        "description": "Product performance report — aggregated from curated_products and curated_order_items. Ranks products by revenue, units sold, and margin. Used by merchandising team for inventory and pricing decisions.",
        "columns": [
            {"name": "product_id", "type": "STRING", "description": "Product SKU"},
            {"name": "product_name", "type": "STRING", "description": "Product name"},
            {"name": "category", "type": "STRING", "description": "Product category"},
            {"name": "total_units_sold", "type": "INTEGER", "description": "Total units sold in period"},
            {"name": "total_revenue_usd", "type": "DECIMAL", "description": "Total revenue in period"},
            {"name": "margin_pct", "type": "DECIMAL", "description": "Profit margin"},
            {"name": "rank_by_revenue", "type": "INTEGER", "description": "Revenue rank within category"},
            {"name": "generated_at", "type": "TIMESTAMP", "description": "When this report was generated"},
        ],
    },
    {
        "name": "rpt_shipping_sla",
        "layer": "reporting",
        "description": "Shipping SLA compliance report — tracks delivery performance by carrier. Calculates percentage of orders delivered within SLA (3 business days). Used by operations team to evaluate logistics partners.",
        "columns": [
            {"name": "carrier", "type": "STRING", "description": "Shipping carrier"},
            {"name": "total_shipments", "type": "INTEGER", "description": "Number of shipments"},
            {"name": "on_time_pct", "type": "DECIMAL", "description": "Percentage delivered within SLA"},
            {"name": "avg_delivery_days", "type": "DECIMAL", "description": "Average days from order to delivery"},
            {"name": "return_rate", "type": "DECIMAL", "description": "Percentage of shipments returned"},
            {"name": "report_period", "type": "STRING", "description": "Reporting period (e.g., '2026-W34')"},
            {"name": "generated_at", "type": "TIMESTAMP", "description": "When this report was generated"},
        ],
    },
    {
        "name": "rpt_revenue_by_country",
        "layer": "reporting",
        "description": "Revenue breakdown by customer country — aggregated from curated_orders and curated_customers. Shows geographic distribution of sales. Powers the regional sales dashboard and helps identify expansion opportunities.",
        "columns": [
            {"name": "country_code", "type": "STRING", "description": "ISO country code"},
            {"name": "country_name", "type": "STRING", "description": "Full country name"},
            {"name": "total_orders", "type": "INTEGER", "description": "Number of orders from this country"},
            {"name": "total_revenue_usd", "type": "DECIMAL", "description": "Total revenue from this country"},
            {"name": "customer_count", "type": "INTEGER", "description": "Number of unique customers"},
            {"name": "avg_order_value_usd", "type": "DECIMAL", "description": "Average order value"},
            {"name": "report_period", "type": "STRING", "description": "Reporting period"},
            {"name": "generated_at", "type": "TIMESTAMP", "description": "When this report was generated"},
        ],
    },
]


# =============================================================================
# JOB / PIPELINE DEFINITIONS
# =============================================================================
# These define the ETL jobs and their lineage — which tables each job reads
# from and writes to. This is the core of the lineage graph.
#
# Think of each job as an Airflow DAG task, a dbt model, or a Spark job.

JOBS = [
    # ---- Raw → Staging jobs ----
    {
        "name": "ingest_orders",
        "description": "Extracts orders from source database and loads into raw_orders. Runs every 15 minutes via CDC (Change Data Capture).",
        "schedule": "*/15 * * * *",
        "reads": [],
        "writes": ["raw_orders"],
        "owner": "data_engineering",
    },
    {
        "name": "ingest_customers",
        "description": "Daily full extract of customer data from CRM into raw_customers.",
        "schedule": "0 2 * * *",
        "reads": [],
        "writes": ["raw_customers"],
        "owner": "data_engineering",
    },
    {
        "name": "ingest_payments",
        "description": "Extracts payment transactions from Stripe API into raw_payments. Runs hourly.",
        "schedule": "0 * * * *",
        "reads": [],
        "writes": ["raw_payments"],
        "owner": "data_engineering",
    },
    {
        "name": "ingest_products",
        "description": "Daily extract of product catalog from inventory system into raw_products.",
        "schedule": "0 3 * * *",
        "reads": [],
        "writes": ["raw_products"],
        "owner": "data_engineering",
    },
    {
        "name": "ingest_order_items",
        "description": "Extracts order line items from source database into raw_order_items. Runs with ingest_orders.",
        "schedule": "*/15 * * * *",
        "reads": [],
        "writes": ["raw_order_items"],
        "owner": "data_engineering",
    },
    {
        "name": "ingest_shipping",
        "description": "Polls logistics partner APIs for new shipping events. Loads into raw_shipping_events. Runs every 30 minutes.",
        "schedule": "*/30 * * * *",
        "reads": [],
        "writes": ["raw_shipping_events"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_orders",
        "description": "Cleans and validates raw orders. Removes test orders, deduplicates by order_id, standardizes timestamps to UTC. Produces stg_orders.",
        "schedule": "*/15 * * * *",
        "reads": ["raw_orders"],
        "writes": ["stg_orders"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_customers",
        "description": "Cleans customer data: validates emails, normalizes country codes, combines first/last name. Produces stg_customers.",
        "schedule": "0 3 * * *",
        "reads": ["raw_customers"],
        "writes": ["stg_customers"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_payments",
        "description": "Cleans payment data: converts currencies to USD, deduplicates by idempotency key. Produces stg_payments.",
        "schedule": "0 * * * *",
        "reads": ["raw_payments"],
        "writes": ["stg_payments"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_products",
        "description": "Cleans product catalog: standardizes categories, validates prices. Produces stg_products.",
        "schedule": "0 4 * * *",
        "reads": ["raw_products"],
        "writes": ["stg_products"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_order_items",
        "description": "Cleans order line items: validates quantities and prices, removes orphaned records. Produces stg_order_items.",
        "schedule": "*/15 * * * *",
        "reads": ["raw_order_items"],
        "writes": ["stg_order_items"],
        "owner": "data_engineering",
    },
    {
        "name": "stage_shipping",
        "description": "Cleans shipping events: deduplicates, normalizes carrier names and event types. Produces stg_shipping.",
        "schedule": "*/30 * * * *",
        "reads": ["raw_shipping_events"],
        "writes": ["stg_shipping"],
        "owner": "data_engineering",
    },

    # ---- Staging → Curated jobs ----
    {
        "name": "build_curated_orders",
        "description": "Builds the conformed order fact table by joining stg_orders with stg_payments (for payment status) and stg_shipping (for delivery status). Applies business rules for refund classification. This is the most critical transformation in the pipeline.",
        "schedule": "30 * * * *",
        "reads": ["stg_orders", "stg_payments", "stg_shipping"],
        "writes": ["curated_orders"],
        "owner": "analytics_engineering",
    },
    {
        "name": "build_curated_customers",
        "description": "Builds the customer dimension by enriching stg_customers with order metrics from curated_orders: total orders, lifetime value, first/last order dates.",
        "schedule": "0 5 * * *",
        "reads": ["stg_customers", "curated_orders"],
        "writes": ["curated_customers"],
        "owner": "analytics_engineering",
    },
    {
        "name": "build_curated_products",
        "description": "Builds the product dimension by enriching stg_products with sales metrics from stg_order_items: total units sold, revenue, margin calculations.",
        "schedule": "0 5 * * *",
        "reads": ["stg_products", "stg_order_items"],
        "writes": ["curated_products"],
        "owner": "analytics_engineering",
    },
    {
        "name": "build_curated_order_items",
        "description": "Builds conformed line items by joining stg_order_items with product pricing. Computes line totals including discounts.",
        "schedule": "30 * * * *",
        "reads": ["stg_order_items", "stg_products"],
        "writes": ["curated_order_items"],
        "owner": "analytics_engineering",
    },

    # ---- Curated → Reporting jobs ----
    {
        "name": "generate_daily_sales",
        "description": "Generates the daily sales summary report from curated_orders. Calculates total revenue, order count, average order value, and refund rate per day. Runs at 6 AM daily after curated tables are built.",
        "schedule": "0 6 * * *",
        "reads": ["curated_orders", "curated_order_items"],
        "writes": ["rpt_daily_sales"],
        "owner": "analytics_engineering",
    },
    {
        "name": "generate_customer_segments",
        "description": "Generates customer segmentation report from curated_customers. Computes segment-level metrics for marketing team.",
        "schedule": "0 7 * * *",
        "reads": ["curated_customers", "curated_orders"],
        "writes": ["rpt_customer_segments"],
        "owner": "analytics_engineering",
    },
    {
        "name": "generate_product_performance",
        "description": "Generates product performance rankings from curated_products and curated_order_items. Used by merchandising for inventory decisions.",
        "schedule": "0 7 * * *",
        "reads": ["curated_products", "curated_order_items"],
        "writes": ["rpt_product_performance"],
        "owner": "analytics_engineering",
    },
    {
        "name": "generate_shipping_sla",
        "description": "Generates shipping SLA compliance report by analyzing delivery times from stg_shipping against curated_orders. Evaluates carrier performance.",
        "schedule": "0 8 * * *",
        "reads": ["stg_shipping", "curated_orders"],
        "writes": ["rpt_shipping_sla"],
        "owner": "analytics_engineering",
    },
    {
        "name": "generate_revenue_by_country",
        "description": "Generates geographic revenue breakdown from curated_orders and curated_customers. Powers the regional sales dashboard.",
        "schedule": "0 8 * * *",
        "reads": ["curated_orders", "curated_customers"],
        "writes": ["rpt_revenue_by_country"],
        "owner": "analytics_engineering",
    },
]


# =============================================================================
# GENERATE SYNTHETIC JOB RUN HISTORY
# =============================================================================
# Create realistic job run history — some succeed, some fail.
# This data will be used later for "why did X fail?" questions.

def generate_job_runs(jobs, num_days=7):
    """Generate synthetic job run history for the past N days."""
    runs = []
    base_time = datetime(2026, 8, 23, 0, 0, 0)
    random.seed(42)  # Reproducible

    for day_offset in range(num_days):
        run_date = base_time - timedelta(days=day_offset)
        for job in jobs:
            # Parse schedule to determine how many times per day
            # Simplified: just run each job 1-3 times per day
            num_runs = 1 if job["schedule"].startswith("0") else random.randint(1, 3)

            for run_idx in range(num_runs):
                run_time = run_date + timedelta(
                    hours=random.randint(0, 23),
                    minutes=random.randint(0, 59),
                )

                # 90% success rate, 10% failure
                if random.random() < 0.10:
                    status = "failed"
                    error_messages = [
                        "Connection timeout to source database after 30s",
                        "Schema mismatch: column 'amount' expected DECIMAL but got STRING",
                        "Out of memory: job exceeded 8GB heap limit",
                        "Duplicate key violation on primary key constraint",
                        "Source API returned HTTP 503 Service Unavailable",
                        "Data quality check failed: null rate for order_id exceeded 5% threshold",
                        "Partition not found: source table partition for date not available yet",
                    ]
                    error = random.choice(error_messages)
                    duration_seconds = random.randint(5, 60)
                else:
                    status = "success"
                    error = None
                    duration_seconds = random.randint(30, 600)

                runs.append({
                    "job_name": job["name"],
                    "run_id": f"{job['name']}_{run_date.strftime('%Y%m%d')}_{run_idx}",
                    "started_at": run_time.isoformat(),
                    "duration_seconds": duration_seconds,
                    "status": status,
                    "error_message": error,
                    "records_processed": random.randint(100, 50000) if status == "success" else 0,
                })

    return runs


# =============================================================================
# MAIN: Generate and save all data
# =============================================================================

def main():
    """Generate all synthetic data and write to JSON files."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ---- Tables ----
    tables_output = []
    for t in TABLES:
        tables_output.append({
            "name": t["name"],
            "layer": t["layer"],
            "description": t["description"],
            "column_count": len(t["columns"]),
        })

    tables_path = os.path.join(OUTPUT_DIR, "tables.json")
    with open(tables_path, "w") as f:
        json.dump(tables_output, f, indent=2)
    print(f"✓ Generated {len(tables_output)} tables → {tables_path}")

    # ---- Columns ----
    columns_output = []
    for t in TABLES:
        for col in t["columns"]:
            columns_output.append({
                "table_name": t["name"],
                "column_name": col["name"],
                "data_type": col["type"],
                "description": col["description"],
            })

    columns_path = os.path.join(OUTPUT_DIR, "columns.json")
    with open(columns_path, "w") as f:
        json.dump(columns_output, f, indent=2)
    print(f"✓ Generated {len(columns_output)} columns → {columns_path}")

    # ---- Jobs ----
    jobs_output = []
    for j in JOBS:
        jobs_output.append({
            "name": j["name"],
            "description": j["description"],
            "schedule": j["schedule"],
            "owner": j["owner"],
        })

    jobs_path = os.path.join(OUTPUT_DIR, "jobs.json")
    with open(jobs_path, "w") as f:
        json.dump(jobs_output, f, indent=2)
    print(f"✓ Generated {len(jobs_output)} jobs → {jobs_path}")

    # ---- Lineage Edges ----
    edges_output = []
    for j in JOBS:
        for read_table in j["reads"]:
            edges_output.append({
                "job_name": j["name"],
                "source_table": read_table,
                "target_table": None,
                "direction": "reads",
            })
        for write_table in j["writes"]:
            edges_output.append({
                "job_name": j["name"],
                "source_table": None,
                "target_table": write_table,
                "direction": "writes",
            })

    edges_path = os.path.join(OUTPUT_DIR, "lineage_edges.json")
    with open(edges_path, "w") as f:
        json.dump(edges_output, f, indent=2)
    print(f"✓ Generated {len(edges_output)} lineage edges → {edges_path}")

    # ---- Job Runs (history) ----
    runs = generate_job_runs(JOBS, num_days=7)
    runs_path = os.path.join(OUTPUT_DIR, "job_runs.json")
    with open(runs_path, "w") as f:
        json.dump(runs, f, indent=2)
    print(f"✓ Generated {len(runs)} job run records → {runs_path}")

    # ---- Summary ----
    print(f"\n{'='*60}")
    print(f"  Synthetic data generation complete!")
    print(f"  Output directory: {OUTPUT_DIR}")
    print(f"{'='*60}")
    print(f"  Tables:        {len(tables_output)} (across {len(set(t['layer'] for t in tables_output))} layers)")
    print(f"  Columns:       {len(columns_output)}")
    print(f"  Jobs:          {len(jobs_output)}")
    print(f"  Lineage edges: {len(edges_output)}")
    print(f"  Job runs:      {len(runs)} (past 7 days)")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
